apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: distributweet
resources:
  - namespace.yaml
  - configmap.yaml
  - kafka.yaml
  - qdrant.yaml
  - embedding-worker.yaml
  - recommendation-api.yaml
